apiVersion: v1
kind: Service
metadata:
  name: qbackup
  namespace: qbackup
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qbackup
  ports:
    - name: http
      port: 80
      targetPort: http
